from pathlib import Path
from typing import Protocol


class FileSystem(Protocol):
    def list_files(self, root: Path) -> list[Path]: ...

    def file_size(self, path: Path) -> int: ...

    def modified_at_timestamp(self, path: Path) -> float: ...

    def read_segment(self, path: Path, offset: int, length: int) -> bytes: ...
