from collections.abc import Iterator
from pathlib import Path
from typing import Protocol


class TapeDrive(Protocol):
    def load_tape(self, tape_id: str) -> None: ...

    def unload_tape(self) -> None: ...

    def current_tape_id(self) -> str: ...

    def read_tape_id(self) -> str:
        """Return the tape_id recorded on the currently-loaded tape's metadata.

        Returns an empty string if no identity is recorded (freshly formatted tape).
        """
        ...

    def remaining_capacity_bytes(self) -> int: ...

    def write_file(self, source_path: Path, destination_name: str) -> None: ...

    def write_bytes(self, destination_name: str, data: bytes) -> None: ...

    def write_stream(
        self, destination_name: str, size_bytes: int, chunks: Iterator[bytes]
    ) -> None: ...

    def read_file(self, name: str) -> bytes: ...

    def read_file_segment(self, name: str, offset: int, length: int) -> bytes: ...

    def list_files(self) -> list[str]: ...
